// elements-data.js — Dados dos 118 elementos
// Compartilhado entre table.js (página principal) e admin.js (painel admin).
// Não contém lógica, só dados — seguro para carregar em qualquer contexto.

const ELEMENTS_LAYOUT = [
  { number: 1,   symbol: "H",   name_pt: "Hidrogênio",       category: "nao-metal",           row: 1,  col: 1  },
  { number: 2,   symbol: "He",  name_pt: "Hélio",             category: "gas-nobre",           row: 1,  col: 18 },
  // Período 2
  { number: 3,   symbol: "Li",  name_pt: "Lítio",             category: "alcali",              row: 2,  col: 1  },
  { number: 4,   symbol: "Be",  name_pt: "Berílio",           category: "alcalino-terroso",    row: 2,  col: 2  },
  { number: 5,   symbol: "B",   name_pt: "Boro",              category: "semimetal",           row: 2,  col: 13 },
  { number: 6,   symbol: "C",   name_pt: "Carbono",           category: "nao-metal",           row: 2,  col: 14 },
  { number: 7,   symbol: "N",   name_pt: "Nitrogênio",        category: "nao-metal",           row: 2,  col: 15 },
  { number: 8,   symbol: "O",   name_pt: "Oxigênio",          category: "nao-metal",           row: 2,  col: 16 },
  { number: 9,   symbol: "F",   name_pt: "Flúor",             category: "halogenio",           row: 2,  col: 17 },
  { number: 10,  symbol: "Ne",  name_pt: "Neônio",            category: "gas-nobre",           row: 2,  col: 18 },
  // Período 3
  { number: 11,  symbol: "Na",  name_pt: "Sódio",             category: "alcali",              row: 3,  col: 1  },
  { number: 12,  symbol: "Mg",  name_pt: "Magnésio",          category: "alcalino-terroso",    row: 3,  col: 2  },
  { number: 13,  symbol: "Al",  name_pt: "Alumínio",          category: "metal-pos-transicao", row: 3,  col: 13 },
  { number: 14,  symbol: "Si",  name_pt: "Silício",           category: "semimetal",           row: 3,  col: 14 },
  { number: 15,  symbol: "P",   name_pt: "Fósforo",           category: "nao-metal",           row: 3,  col: 15 },
  { number: 16,  symbol: "S",   name_pt: "Enxofre",           category: "nao-metal",           row: 3,  col: 16 },
  { number: 17,  symbol: "Cl",  name_pt: "Cloro",             category: "halogenio",           row: 3,  col: 17 },
  { number: 18,  symbol: "Ar",  name_pt: "Argônio",           category: "gas-nobre",           row: 3,  col: 18 },
  // Período 4
  { number: 19,  symbol: "K",   name_pt: "Potássio",          category: "alcali",              row: 4,  col: 1  },
  { number: 20,  symbol: "Ca",  name_pt: "Cálcio",            category: "alcalino-terroso",    row: 4,  col: 2  },
  { number: 21,  symbol: "Sc",  name_pt: "Escândio",          category: "metal-transicao",     row: 4,  col: 3  },
  { number: 22,  symbol: "Ti",  name_pt: "Titânio",           category: "metal-transicao",     row: 4,  col: 4  },
  { number: 23,  symbol: "V",   name_pt: "Vanádio",           category: "metal-transicao",     row: 4,  col: 5  },
  { number: 24,  symbol: "Cr",  name_pt: "Cromo",             category: "metal-transicao",     row: 4,  col: 6  },
  { number: 25,  symbol: "Mn",  name_pt: "Manganês",          category: "metal-transicao",     row: 4,  col: 7  },
  { number: 26,  symbol: "Fe",  name_pt: "Ferro",             category: "metal-transicao",     row: 4,  col: 8  },
  { number: 27,  symbol: "Co",  name_pt: "Cobalto",           category: "metal-transicao",     row: 4,  col: 9  },
  { number: 28,  symbol: "Ni",  name_pt: "Níquel",            category: "metal-transicao",     row: 4,  col: 10 },
  { number: 29,  symbol: "Cu",  name_pt: "Cobre",             category: "metal-transicao",     row: 4,  col: 11 },
  { number: 30,  symbol: "Zn",  name_pt: "Zinco",             category: "metal-transicao",     row: 4,  col: 12 },
  { number: 31,  symbol: "Ga",  name_pt: "Gálio",             category: "metal-pos-transicao", row: 4,  col: 13 },
  { number: 32,  symbol: "Ge",  name_pt: "Germânio",          category: "semimetal",           row: 4,  col: 14 },
  { number: 33,  symbol: "As",  name_pt: "Arsênio",           category: "semimetal",           row: 4,  col: 15 },
  { number: 34,  symbol: "Se",  name_pt: "Selênio",           category: "nao-metal",           row: 4,  col: 16 },
  { number: 35,  symbol: "Br",  name_pt: "Bromo",             category: "halogenio",           row: 4,  col: 17 },
  { number: 36,  symbol: "Kr",  name_pt: "Criptônio",         category: "gas-nobre",           row: 4,  col: 18 },
  // Período 5
  { number: 37,  symbol: "Rb",  name_pt: "Rubídio",           category: "alcali",              row: 5,  col: 1  },
  { number: 38,  symbol: "Sr",  name_pt: "Estrôncio",         category: "alcalino-terroso",    row: 5,  col: 2  },
  { number: 39,  symbol: "Y",   name_pt: "Ítrio",             category: "metal-transicao",     row: 5,  col: 3  },
  { number: 40,  symbol: "Zr",  name_pt: "Zircônio",          category: "metal-transicao",     row: 5,  col: 4  },
  { number: 41,  symbol: "Nb",  name_pt: "Nióbio",            category: "metal-transicao",     row: 5,  col: 5  },
  { number: 42,  symbol: "Mo",  name_pt: "Molibdênio",        category: "metal-transicao",     row: 5,  col: 6  },
  { number: 43,  symbol: "Tc",  name_pt: "Tecnécio",          category: "metal-transicao",     row: 5,  col: 7  },
  { number: 44,  symbol: "Ru",  name_pt: "Rutênio",           category: "metal-transicao",     row: 5,  col: 8  },
  { number: 45,  symbol: "Rh",  name_pt: "Ródio",             category: "metal-transicao",     row: 5,  col: 9  },
  { number: 46,  symbol: "Pd",  name_pt: "Paládio",           category: "metal-transicao",     row: 5,  col: 10 },
  { number: 47,  symbol: "Ag",  name_pt: "Prata",             category: "metal-transicao",     row: 5,  col: 11 },
  { number: 48,  symbol: "Cd",  name_pt: "Cádmio",            category: "metal-transicao",     row: 5,  col: 12 },
  { number: 49,  symbol: "In",  name_pt: "Índio",             category: "metal-pos-transicao", row: 5,  col: 13 },
  { number: 50,  symbol: "Sn",  name_pt: "Estanho",           category: "metal-pos-transicao", row: 5,  col: 14 },
  { number: 51,  symbol: "Sb",  name_pt: "Antimônio",         category: "semimetal",           row: 5,  col: 15 },
  { number: 52,  symbol: "Te",  name_pt: "Telúrio",           category: "semimetal",           row: 5,  col: 16 },
  { number: 53,  symbol: "I",   name_pt: "Iodo",              category: "halogenio",           row: 5,  col: 17 },
  { number: 54,  symbol: "Xe",  name_pt: "Xenônio",           category: "gas-nobre",           row: 5,  col: 18 },
  // Período 6
  { number: 55,  symbol: "Cs",  name_pt: "Césio",             category: "alcali",              row: 6,  col: 1  },
  { number: 56,  symbol: "Ba",  name_pt: "Bário",             category: "alcalino-terroso",    row: 6,  col: 2  },
  { number: 57,  symbol: "La",  name_pt: "Lantânio",          category: "lantanideo",          row: 6,  col: 3  },
  { number: 72,  symbol: "Hf",  name_pt: "Háfnio",            category: "metal-transicao",     row: 6,  col: 4  },
  { number: 73,  symbol: "Ta",  name_pt: "Tântalo",           category: "metal-transicao",     row: 6,  col: 5  },
  { number: 74,  symbol: "W",   name_pt: "Tungstênio",        category: "metal-transicao",     row: 6,  col: 6  },
  { number: 75,  symbol: "Re",  name_pt: "Rênio",             category: "metal-transicao",     row: 6,  col: 7  },
  { number: 76,  symbol: "Os",  name_pt: "Ósmio",             category: "metal-transicao",     row: 6,  col: 8  },
  { number: 77,  symbol: "Ir",  name_pt: "Irídio",            category: "metal-transicao",     row: 6,  col: 9  },
  { number: 78,  symbol: "Pt",  name_pt: "Platina",           category: "metal-transicao",     row: 6,  col: 10 },
  { number: 79,  symbol: "Au",  name_pt: "Ouro",              category: "metal-transicao",     row: 6,  col: 11 },
  { number: 80,  symbol: "Hg",  name_pt: "Mercúrio",          category: "metal-transicao",     row: 6,  col: 12 },
  { number: 81,  symbol: "Tl",  name_pt: "Tálio",             category: "metal-pos-transicao", row: 6,  col: 13 },
  { number: 82,  symbol: "Pb",  name_pt: "Chumbo",            category: "metal-pos-transicao", row: 6,  col: 14 },
  { number: 83,  symbol: "Bi",  name_pt: "Bismuto",           category: "metal-pos-transicao", row: 6,  col: 15 },
  { number: 84,  symbol: "Po",  name_pt: "Polônio",           category: "metal-pos-transicao", row: 6,  col: 16 },
  { number: 85,  symbol: "At",  name_pt: "Ástato",            category: "halogenio",           row: 6,  col: 17 },
  { number: 86,  symbol: "Rn",  name_pt: "Radônio",           category: "gas-nobre",           row: 6,  col: 18 },
  // Período 7
  { number: 87,  symbol: "Fr",  name_pt: "Frâncio",           category: "alcali",              row: 7,  col: 1  },
  { number: 88,  symbol: "Ra",  name_pt: "Rádio",             category: "alcalino-terroso",    row: 7,  col: 2  },
  { number: 89,  symbol: "Ac",  name_pt: "Actínio",           category: "actinideo",           row: 7,  col: 3  },
  { number: 104, symbol: "Rf",  name_pt: "Rutherfórdio",      category: "metal-transicao",     row: 7,  col: 4  },
  { number: 105, symbol: "Db",  name_pt: "Dúbnio",            category: "metal-transicao",     row: 7,  col: 5  },
  { number: 106, symbol: "Sg",  name_pt: "Seabórgio",         category: "metal-transicao",     row: 7,  col: 6  },
  { number: 107, symbol: "Bh",  name_pt: "Bóhrio",            category: "metal-transicao",     row: 7,  col: 7  },
  { number: 108, symbol: "Hs",  name_pt: "Hássio",            category: "metal-transicao",     row: 7,  col: 8  },
  { number: 109, symbol: "Mt",  name_pt: "Meitnério",         category: "metal-transicao",     row: 7,  col: 9  },
  { number: 110, symbol: "Ds",  name_pt: "Darmstádio",        category: "metal-transicao",     row: 7,  col: 10 },
  { number: 111, symbol: "Rg",  name_pt: "Roentgênio",        category: "metal-transicao",     row: 7,  col: 11 },
  { number: 112, symbol: "Cn",  name_pt: "Copernício",        category: "metal-transicao",     row: 7,  col: 12 },
  { number: 113, symbol: "Nh",  name_pt: "Nihônio",           category: "metal-pos-transicao", row: 7,  col: 13 },
  { number: 114, symbol: "Fl",  name_pt: "Fleróvio",          category: "metal-pos-transicao", row: 7,  col: 14 },
  { number: 115, symbol: "Mc",  name_pt: "Moscóvio",          category: "metal-pos-transicao", row: 7,  col: 15 },
  { number: 116, symbol: "Lv",  name_pt: "Livermório",        category: "metal-pos-transicao", row: 7,  col: 16 },
  { number: 117, symbol: "Ts",  name_pt: "Tennessino",        category: "halogenio",           row: 7,  col: 17 },
  { number: 118, symbol: "Og",  name_pt: "Oganessônio",       category: "gas-nobre",           row: 7,  col: 18 },
  // Lantanídeos (row 9)
  { number: 58,  symbol: "Ce",  name_pt: "Cério",             category: "lantanideo",          row: 9,  col: 4  },
  { number: 59,  symbol: "Pr",  name_pt: "Praseodímio",       category: "lantanideo",          row: 9,  col: 5  },
  { number: 60,  symbol: "Nd",  name_pt: "Neodímio",          category: "lantanideo",          row: 9,  col: 6  },
  { number: 61,  symbol: "Pm",  name_pt: "Promécio",          category: "lantanideo",          row: 9,  col: 7  },
  { number: 62,  symbol: "Sm",  name_pt: "Samário",           category: "lantanideo",          row: 9,  col: 8  },
  { number: 63,  symbol: "Eu",  name_pt: "Európio",           category: "lantanideo",          row: 9,  col: 9  },
  { number: 64,  symbol: "Gd",  name_pt: "Gadolínio",         category: "lantanideo",          row: 9,  col: 10 },
  { number: 65,  symbol: "Tb",  name_pt: "Térbio",            category: "lantanideo",          row: 9,  col: 11 },
  { number: 66,  symbol: "Dy",  name_pt: "Disprósio",         category: "lantanideo",          row: 9,  col: 12 },
  { number: 67,  symbol: "Ho",  name_pt: "Hólmio",            category: "lantanideo",          row: 9,  col: 13 },
  { number: 68,  symbol: "Er",  name_pt: "Érbio",             category: "lantanideo",          row: 9,  col: 14 },
  { number: 69,  symbol: "Tm",  name_pt: "Túlio",             category: "lantanideo",          row: 9,  col: 15 },
  { number: 70,  symbol: "Yb",  name_pt: "Itérbio",           category: "lantanideo",          row: 9,  col: 16 },
  { number: 71,  symbol: "Lu",  name_pt: "Lutécio",           category: "lantanideo",          row: 9,  col: 17 },
  // Actinídeos (row 10)
  { number: 90,  symbol: "Th",  name_pt: "Tório",             category: "actinideo",           row: 10, col: 4  },
  { number: 91,  symbol: "Pa",  name_pt: "Protactínio",       category: "actinideo",           row: 10, col: 5  },
  { number: 92,  symbol: "U",   name_pt: "Urânio",            category: "actinideo",           row: 10, col: 6  },
  { number: 93,  symbol: "Np",  name_pt: "Netúnio",           category: "actinideo",           row: 10, col: 7  },
  { number: 94,  symbol: "Pu",  name_pt: "Plutônio",          category: "actinideo",           row: 10, col: 8  },
  { number: 95,  symbol: "Am",  name_pt: "Amerício",          category: "actinideo",           row: 10, col: 9  },
  { number: 96,  symbol: "Cm",  name_pt: "Cúrio",             category: "actinideo",           row: 10, col: 10 },
  { number: 97,  symbol: "Bk",  name_pt: "Berquélio",         category: "actinideo",           row: 10, col: 11 },
  { number: 98,  symbol: "Cf",  name_pt: "Califórnio",        category: "actinideo",           row: 10, col: 12 },
  { number: 99,  symbol: "Es",  name_pt: "Einsteínio",        category: "actinideo",           row: 10, col: 13 },
  { number: 100, symbol: "Fm",  name_pt: "Férmio",            category: "actinideo",           row: 10, col: 14 },
  { number: 101, symbol: "Md",  name_pt: "Mendelévio",        category: "actinideo",           row: 10, col: 15 },
  { number: 102, symbol: "No",  name_pt: "Nobélio",           category: "actinideo",           row: 10, col: 16 },
  { number: 103, symbol: "Lr",  name_pt: "Laurêncio",         category: "actinideo",           row: 10, col: 17 },
];
